dist: trusty
sudo: false
language: java
jdk: 
  - openjdk13
  - oraclejdk13
cache:
  bundler: true
  directories:
    - '$HOME/.m2'
install: /bin/true
script:
  - 'mvn clean'
  - 'mvn test'
  - 'mvn install -DskipTests=true'
#before_deploy:
#  - 'git config --local user.name "YOUR GIT USER NAME"'
#  - 'git config --local user.email "YOUR GIT USER EMAIL"'
#  - 'export TRAVIS_TAG=${TRAVIS_TAG:-$(date +''%Y%m%d%H%M%S'')-$(git log --format=%h -1)}'
#  - 'git tag $TRAVIS_TAG'
#deploy:
#  skip_cleanup: true
#  provider: releases
#  api_key:
#    secure: 
#  on:
#    repo: 
#    branch: 'release'